version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/xissy/swagger-tool
    steps:
      - checkout
      - run: curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: dep ensure
      - run: go test -v -cover ./...
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: gometalinter --disable=golint --deadline=60s -s vendor ./...
